import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../../models/models.dart';
import '../../models/user_profile.dart';

class PdfGenerator {
  static Future<Uint8List> generateKundaliReport(UserProfile profile, Kundali kundali) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Text('CosmicVed — Birth Chart Report', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
              ),
              pw.SizedBox(height: 20),
              
              // Profile Info
              pw.Text('Name: ${profile.name}', style: const pw.TextStyle(fontSize: 16)),
              pw.Text('Date of Birth: ${profile.dateOfBirth}', style: const pw.TextStyle(fontSize: 14)),
              pw.Text('Time of Birth: ${profile.timeOfBirth}', style: const pw.TextStyle(fontSize: 14)),
              pw.Text('Place of Birth: ${profile.birthCity}, ${profile.birthCountry}', style: const pw.TextStyle(fontSize: 14)),
              pw.SizedBox(height: 20),
              
              // Astrological Highlights
              pw.Text('Astrological Details', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
              pw.Divider(),
              pw.Text('Ascendant (Lagna): ${kundali.ascendantSign} (${kundali.ascendantDegrees.toStringAsFixed(2)}°)'),
              pw.Text('Moon Sign (Rashi): ${kundali.moonSign}'),
              pw.Text('Sun Sign: ${kundali.sunSign}'),
              pw.Text('Birth Nakshatra: ${kundali.moonNakshatra} (Pada ${kundali.moonNakshatraPada})'),
              pw.Text('Ayanamsa (Lahiri): ${kundali.ayanamsa.toStringAsFixed(4)}°'),
              pw.SizedBox(height: 20),
              
              // Planetary Positions Table
              pw.Text('Planetary Positions', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 10),
              pw.TableHelper.fromTextArray(
                context: context,
                headers: ['Planet', 'Sign', 'Degree', 'House', 'Nakshatra'],
                data: kundali.planets.map((p) => [
                  p.name,
                  _getRashiName(p.rashiIndex),
                  '${p.rashiDegrees.toStringAsFixed(2)}°',
                  p.houseNumber.toString(),
                  p.nakshatra ?? '-',
                ]).toList(),
              ),
              
              pw.Spacer(),
              pw.Align(
                alignment: pw.Alignment.center,
                child: pw.Text(
                  'Generated by CosmicVed Astrology Engine',
                  style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey),
                ),
              ),
            ],
          );
        },
      ),
    );

    return pdf.save();
  }
  
  static String _getRashiName(int index) {
    const rashiNames = ['Aries', 'Taurus', 'Gemini', 'Cancer', 'Leo', 'Virgo', 'Libra', 'Scorpio', 'Sagittarius', 'Capricorn', 'Aquarius', 'Pisces'];
    return rashiNames[index % 12];
  }
}
